### ISSUE TITLE
Aydin Orhan removed from credits

### ISSUE THREAD

**Issue by JavaRip** [gdscports/react-snake#30]
https://github.com/gdscports/react-snake/pull/27 this merge deleted Aydin Orhan from the credits

Sorry Aydin! My bad!

This is an example of a bodged code review & merge

**Comment by Beamedy** [comment]
oh sorry my bad, maybe I selected his name by mistake when I typed mine, I will correct it

**Comment by Beamedy** [comment]
merge #31 corrected this issue
